import json 
from llm import chat

def critic_agent(text:str) -> dict:
    """This agent will critique the humanised version of text generated by draft agent."""

    prompt = open("prompts/critic.md").read().format(text=text)
    response = chat(prompt)
    
    try: 
       """Parse the response as JSON"""
       parsed = json.loads(response)
       if "score" in parsed and "crtique" in parsed:
           return parsed
       
    except:
        pass

    fix_prompt = f""" 
The following response was not in valid JSON format:
Rewrite it to be valid JSON with the keys 'score' and 'crtique'.

response: {response}
"""
    try:
        response = chat(fix_prompt)
        parsed = json.loads(response)
        return parsed
    except: 
        pass

    return {"score": 5, "critique": "Model returned invalid JSON earlier."}